import Head from "next/head";
import { Inter } from "next/font/google";
import { useState } from "react";
import About from "@/components/About";
import Portfolio from "@/components/Portfolio";
import Services from "@/components/Services";

const inter = Inter({ subsets: ["latin"] }); // revisar esto

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  const [isOpen1, setIsOpen1] = useState(false);
  const [isOpen2, setIsOpen2] = useState(false);

  function handleToggle1() {
    setIsOpen1(!isOpen1);
  }
  function handleToggle2() {
    setIsOpen2(!isOpen2);
  }
  return (
    <div
      className={`font-sans ${
        darkMode ? "bg-gray-900 text-gray-100 dark" : "bg-white text-gray-800"
      }`}
    >
      <Head>
        <title>Ignacio Barra Portfolio</title>
        <meta name="description" content="Generated by cre"></meta>
        <link rel="icon" href="/favicon.ico"></link>
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <About darkMode={darkMode} setDarkMode={setDarkMode} />

        <Services />

        <Portfolio
          handleToggle1={handleToggle1}
          isOpen1={isOpen1}
          setIsOpen1={setIsOpen1}
          handleToggle2={handleToggle2}
          isOpen2={isOpen2}
          setIsOpen2={setIsOpen2}
        />
      </main>
    </div>
  );
}
