import Head from "next/head";
import { Inter } from "next/font/google";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedIn,
  AiFillYoutube,
} from "react-icons/ai";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ignacio Barra's Portfolio</title>
        <meta name="description" content="Generated by cre"></meta>
        <link rel="icon" href="/favicon.ico"></link>
      </Head>
      <main className="bg-white px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">Developed by Igna</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div>
            <h2>Ignacio Barra</h2>
            <h3>Full Stack Developer</h3>
            <p>
              Hi, I'm a Full Stack Developer. I would say very friendly and a
              team worker, i have mixed my skills from psychology to this new
              career path in tech, i really like traveling and meeting different
              cultures.
            </p>
          </div>
          <div>
            <AiFillTwitterCircle />
          </div>
        </section>
      </main>
    </div>
  );
}
